name: React Native CI

on:
  push:
    branches: [main, develop, M-Init]
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 25
          cache: npm

      - run: npm ci

      - run: npm run lint

      # Uncomment if have tests
      # - run: npm test
